version: "3.8"

services:
  data-transformation:
    build: .
    container_name: data_transformation
    volumes:
      - .:/var/task
      - ./profiles:/var/task/profiles
    environment:
      - DBT_PROFILES_DIR=/var/task/profiles
      - DBT_PROJECT_DIR=/var/task
    env_file:
      - .env
    command: dbt run --profiles-dir /var/task/profiles

  data-transformation-dev:
    build: .
    container_name: data_transformation_dev
    volumes:
      - .:/var/task
      - ./profiles:/var/task/profiles
    environment:
      - DBT_PROFILES_DIR=/var/task/profiles
      - DBT_PROJECT_DIR=/var/task
    env_file:
      - .env
    command: dbt run --target dev --profiles-dir /var/task/profiles

  data-transformation-test:
    build: .
    container_name: data_transformation_test
    volumes:
      - .:/var/task
      - ./profiles:/var/task/profiles
    environment:
      - DBT_PROFILES_DIR=/var/task/profiles
      - DBT_PROJECT_DIR=/var/task
    env_file:
      - .env
    command: dbt test --profiles-dir /var/task/profiles
